steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=portfolio-website
      - --key=cloudbuild-env
  # Insert other build steps here

  # Update Node version
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["update", "npm", "-g"]

  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Deploy
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "deploy"]
